name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        options: >-
          --name mongodb
          --health-cmd "mongo --eval 'db.runCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10

    env:
      MONGO_URL: mongodb://localhost:27017/testdb

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Wait for MongoDB to be ready
        run: |
          for i in {60..0}; do
            nc -z localhost 27017 && break
            echo 'Waiting for MongoDB...'
            sleep 2
          done
          if [ "$i" = 0 ]; then
            echo 'MongoDB did not start in time' >&2
            docker logs mongodb
            exit 1
          fi

      - name: Run tests
        run: npm run test

      - name: Build project
        run: npm run build

      - name: Lint project
        run: npm run lint

      - name: Output MongoDB logs for debugging
        if: failure()
        run: docker logs mongodb
